[package]
name = "datafusion-federation"
version= "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
metadata = "test"

[lib]
name = "datafusion_federation"
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
datafusion.workspace = true
