name: Release

on:
  push:
    branches:
      - main
      - AppIntegration
    paths:
      - datafusion-federation/src/**

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-smart-release --debug --locked
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo check
      - run: cargo changelog --execute datafusion-federation
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APPID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo smart-release \
            --update-crates-index \
            --allow-fully-generated-changelogs \
            --execute \
            --no-publish \
            --no-changelog-preview \
            --allow-dirty \
            --verbose \
            datafusion-federation
